name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter
        run: |
          flake8 src/ --statistics
          
      - name: Run unit tests
        run: |
          pytest src/tests/unit

      - name: Build executable with PyInstaller using spec file
        run: |
          pip install pyinstaller
          pyinstaller src/backend/app/app.spec  # Use the spec file for building

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3  # Update to v3
        with:
          name: flask-app-executable
          path: dist/app  # Path to your built executable
